### PR TITLE
Added example notebooks.

### PR DESCRIPTION
**Pull request by timothyrenner**
Changes proposed in this pull request:
- Adds some notebook examples to accompany the blog post.

@ExpediaGroup/map-maker-committers

### CODE REVIEW

**Comment by kwmsmith** [comment]
> If your map needs seem a little too complicated

Is this a typo?  It doesn't parse right away -- maybe "If you need lower-level control for complex interactions and whatnot..."

**Comment by kwmsmith** [comment]
It would increase the impact of the notebooks if they included a static html version of the plots in the GH rendering.  Without notebook visualizations it might seem like map-maker is broken to newcomers.

**Review by kwmsmith — APPROVED** [review]
One possible typo and a suggestion, otherwise LGTM.

**Comment by timothyrenner** [comment]
There's not an easy way to render the interactive maps without GH pages, but what I can do is add some screenshots next to the interactive maps with a note about it.

**Pull request merged**
